changelog:
  exclude:
    labels:
      - ignore-for-release
      - no-release-notes
      - skip-release-notes
    authors:
      - github-actions[bot]
      - dependabot[bot]
  categories:
    - title: Breaking Changes
      labels:
        - breaking
        - semver-major
    - title: Features
      labels:
        - feat
        - feature
        - enhancement
    - title: Fixes
      labels:
        - fix
        - bug
        - bugfix
    - title: Security
      labels:
        - security
    - title: Documentation
      labels:
        - docs
        - documentation
    - title: Maintenance
      labels:
        - chore
        - ci
        - build
        - refactor
        - dependencies
